### ISSUE TITLE
Upgrading to kirkstone

### ISSUE THREAD

**Issue by DvirB10** [octavosystems/meta-octavo-osd32mp1#1]
Hey!
we want to upgrade our build system to kirkstone, and I wonder if you are going to upgrade your layer.
meta-st-stm32 has already been updated.
Thank you,
Dvir.

**Comment by yishai1999** [comment]
@neerajdantu Is this going to be done?

**Comment by grahas** [comment]
@neerajdantu Is this going to be done? x2?

**Comment by neerajdantu** [comment]
Hey Dvir, 

Please see https://github.com/octavosystems/meta-octavo-osd32mp1/tree/kirkstone. The branch will get more updates, but should be minor.

Best,
Neeraj
